//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnofficialDDNS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnofficialDDNS.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start service. Main registry key missing:.
        /// </summary>
        internal static string Event10000 {
            get {
                return ResourceManager.GetString("Event10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start service. Registry value interval_minutes is missing or not a DWORD..
        /// </summary>
        internal static string Event10001 {
            get {
                return ResourceManager.GetString("Event10001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start service. Registry value interval_minutes_error is missing or not a DWORD..
        /// </summary>
        internal static string Event10002 {
            get {
                return ResourceManager.GetString("Event10002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start service. Registry value registrar is missing or not a String..
        /// </summary>
        internal static string Event10003 {
            get {
                return ResourceManager.GetString("Event10003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start service. Registry value username is missing or not a String..
        /// </summary>
        internal static string Event10004 {
            get {
                return ResourceManager.GetString("Event10004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start service. Registry value apitoken is missing or not a Binary..
        /// </summary>
        internal static string Event10005 {
            get {
                return ResourceManager.GetString("Event10005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start service. Registry value apitoken has invalid data..
        /// </summary>
        internal static string Event10006 {
            get {
                return ResourceManager.GetString("Event10006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start service. Registry value domain is missing or not a String..
        /// </summary>
        internal static string Event10007 {
            get {
                return ResourceManager.GetString("Event10007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start service. Registry value interval_minutes must be greater than 0..
        /// </summary>
        internal static string Event10100 {
            get {
                return ResourceManager.GetString("Event10100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start service. Registry value interval_minutes_error must be greater than 0..
        /// </summary>
        internal static string Event10101 {
            get {
                return ResourceManager.GetString("Event10101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start service. Registry value registrar must be namedotcom..
        /// </summary>
        internal static string Event10102 {
            get {
                return ResourceManager.GetString("Event10102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start service. Registry value username must not be empty..
        /// </summary>
        internal static string Event10103 {
            get {
                return ResourceManager.GetString("Event10103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start service. Registry value domain must not be empty..
        /// </summary>
        internal static string Event10104 {
            get {
                return ResourceManager.GetString("Event10104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestJSON: API responded with non-200 HTTP code..
        /// </summary>
        internal static string Event10300 {
            get {
                return ResourceManager.GetString("Event10300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestJSON: Got exception while querying API..
        /// </summary>
        internal static string Event10301 {
            get {
                return ResourceManager.GetString("Event10301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestJSON: Invalid JSON from API..
        /// </summary>
        internal static string Event10302 {
            get {
                return ResourceManager.GetString("Event10302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetCurrentIP: Missing result code and/or message in JSON from API..
        /// </summary>
        internal static string Event10400 {
            get {
                return ResourceManager.GetString("Event10400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetCurrentIP: API responded with non-100 API code. Message:.
        /// </summary>
        internal static string Event10401 {
            get {
                return ResourceManager.GetString("Event10401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetCurrentIP: Invalid JSON from API, missing client_ip..
        /// </summary>
        internal static string Event10402 {
            get {
                return ResourceManager.GetString("Event10402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetCurrentIP: API did not provide a valid IP address..
        /// </summary>
        internal static string Event10403 {
            get {
                return ResourceManager.GetString("Event10403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate: Missing result code and/or message in JSON from API..
        /// </summary>
        internal static string Event10410 {
            get {
                return ResourceManager.GetString("Event10410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate: API responded with non-100 API code. Message:.
        /// </summary>
        internal static string Event10411 {
            get {
                return ResourceManager.GetString("Event10411", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate: Invalid JSON from API, missing session_token..
        /// </summary>
        internal static string Event10412 {
            get {
                return ResourceManager.GetString("Event10412", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate: API did not provide a valid session token..
        /// </summary>
        internal static string Event10413 {
            get {
                return ResourceManager.GetString("Event10413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPriDomain: Missing result code and/or message in JSON from API..
        /// </summary>
        internal static string Event10420 {
            get {
                return ResourceManager.GetString("Event10420", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPriDomain: API responded with non-100 API code. Message:.
        /// </summary>
        internal static string Event10421 {
            get {
                return ResourceManager.GetString("Event10421", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPriDomain: Found no domains associated with account..
        /// </summary>
        internal static string Event10422 {
            get {
                return ResourceManager.GetString("Event10422", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPriDomain: No access to the domain..
        /// </summary>
        internal static string Event10423 {
            get {
                return ResourceManager.GetString("Event10423", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetRecords: Missing result code and/or message in JSON from API..
        /// </summary>
        internal static string Event10430 {
            get {
                return ResourceManager.GetString("Event10430", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetRecords: API responded with non-100 API code. Message:.
        /// </summary>
        internal static string Event10431 {
            get {
                return ResourceManager.GetString("Event10431", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateDNSRecord (delete): Missing result code and/or message in JSON from API..
        /// </summary>
        internal static string Event10440 {
            get {
                return ResourceManager.GetString("Event10440", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateDNSRecord (delete): API responded with non-100 API code. Message:.
        /// </summary>
        internal static string Event10441 {
            get {
                return ResourceManager.GetString("Event10441", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateDNSRecord (create): Missing result code and/or message in JSON from API..
        /// </summary>
        internal static string Event10442 {
            get {
                return ResourceManager.GetString("Event10442", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateDNSRecord (create): API responded with non-100 API code. Message:.
        /// </summary>
        internal static string Event10443 {
            get {
                return ResourceManager.GetString("Event10443", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateDNSRecord: Updated domain record with the public IP address..
        /// </summary>
        internal static string Event10444 {
            get {
                return ResourceManager.GetString("Event10444", resourceCulture);
            }
        }
    }
}
