//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDDNSQuery {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UDDNSQuery.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username field is empty..
        /// </summary>
        internal static string Error100 {
            get {
                return ResourceManager.GetString("Error100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API token field is empty..
        /// </summary>
        internal static string Error101 {
            get {
                return ResourceManager.GetString("Error101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain name field is empty..
        /// </summary>
        internal static string Error102 {
            get {
                return ResourceManager.GetString("Error102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API responded with non-200 HTTP code..
        /// </summary>
        internal static string Error200 {
            get {
                return ResourceManager.GetString("Error200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got exception while querying API..
        /// </summary>
        internal static string Error201 {
            get {
                return ResourceManager.GetString("Error201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON from API..
        /// </summary>
        internal static string Error202 {
            get {
                return ResourceManager.GetString("Error202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing result code and/or message in JSON from API..
        /// </summary>
        internal static string Error300 {
            get {
                return ResourceManager.GetString("Error300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API responded with non-100 API code. Message:.
        /// </summary>
        internal static string Error301 {
            get {
                return ResourceManager.GetString("Error301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON from API, missing client_ip..
        /// </summary>
        internal static string Error302 {
            get {
                return ResourceManager.GetString("Error302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API did not provide a valid IP address..
        /// </summary>
        internal static string Error303 {
            get {
                return ResourceManager.GetString("Error303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing result code and/or message in JSON from API..
        /// </summary>
        internal static string Error400 {
            get {
                return ResourceManager.GetString("Error400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API responded with non-100 API code. Message:.
        /// </summary>
        internal static string Error401 {
            get {
                return ResourceManager.GetString("Error401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON from API, missing session_token..
        /// </summary>
        internal static string Error402 {
            get {
                return ResourceManager.GetString("Error402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API did not provide a valid session token..
        /// </summary>
        internal static string Error403 {
            get {
                return ResourceManager.GetString("Error403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPriDomain: Missing result code and/or message in JSON from API..
        /// </summary>
        internal static string Error500 {
            get {
                return ResourceManager.GetString("Error500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPriDomain: API responded with non-100 API code. Message:.
        /// </summary>
        internal static string Error501 {
            get {
                return ResourceManager.GetString("Error501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPriDomain: Found no domains associated with account..
        /// </summary>
        internal static string Error502 {
            get {
                return ResourceManager.GetString("Error502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPriDomain: No access to the domain..
        /// </summary>
        internal static string Error503 {
            get {
                return ResourceManager.GetString("Error503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing result code and/or message in JSON from API..
        /// </summary>
        internal static string Error600 {
            get {
                return ResourceManager.GetString("Error600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API responded with non-100 API code. Message:.
        /// </summary>
        internal static string Error601 {
            get {
                return ResourceManager.GetString("Error601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateDNSRecord (delete): Missing result code and/or message in JSON from API..
        /// </summary>
        internal static string Error700 {
            get {
                return ResourceManager.GetString("Error700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateDNSRecord (delete): API responded with non-100 API code. Message:.
        /// </summary>
        internal static string Error701 {
            get {
                return ResourceManager.GetString("Error701", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateDNSRecord (create): Missing result code and/or message in JSON from API..
        /// </summary>
        internal static string Error702 {
            get {
                return ResourceManager.GetString("Error702", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateDNSRecord (create): API responded with non-100 API code. Message:.
        /// </summary>
        internal static string Error703 {
            get {
                return ResourceManager.GetString("Error703", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateDNSRecord: Updated domain record with the public IP address..
        /// </summary>
        internal static string Error704 {
            get {
                return ResourceManager.GetString("Error704", resourceCulture);
            }
        }
    }
}
